"""
=========================================================
Module      : engineer.py

System      : AWOS

Component   : Engineer Agent

Purpose
-------
Executes the engineering workflow using
the GitHub MCP Server.

Workflow
--------
1. Create Repository
2. Create Branch
3. Create README
4. Update README
5. Create Pull Request
=========================================================
"""

from pydantic import BaseModel

from app.mcp.manager import mcp_manager


class EngineerResult(BaseModel):
    completed: bool
    actions: list[str]


class EngineerAgent:

    async def execute(
        self,
        repo_name: str,
        description: str,
        owner: str,
    ) -> EngineerResult:

        actions = []

        # ------------------------------------------------
        # 1. Create Repository
        # ------------------------------------------------

        repository = await mcp_manager.call(
            server="github",
            tool="create_github_repository",
            arguments={
                "repo_name": repo_name,
                "description": description,
                "private": False,
            },
        )

        if repository["status"] != "success":
            return EngineerResult(
                completed=False,
                actions=[repository["message"]],
            )

        actions.append(repository["message"])

        # ------------------------------------------------
        # 2. Create Branch
        # ------------------------------------------------

        branch = await mcp_manager.call(
            server="github",
            tool="create_repository_branch",
            arguments={
                "owner": owner,
                "repo_name": repo_name,
                "branch_name": "feature/awos",
                "source_branch": "main",
            },
        )

        actions.append(branch["message"])

        # ------------------------------------------------
        # 3. Create README
        # ------------------------------------------------

        readme = await mcp_manager.call(
            server="github",
            tool="create_repository_file",
            arguments={
                "owner": owner,
                "repo_name": repo_name,
                "file_path": "README.md",
                "content": "# AWOS\n\nGenerated by AWOS",
                "commit_message": "Initial README",
                "branch": "feature/awos",
            },
        )

        actions.append(readme["message"])

        # ------------------------------------------------
        # 4. Update README
        # ------------------------------------------------

        update = await mcp_manager.call(
            server="github",
            tool="update_repository_file",
            arguments={
                "owner": owner,
                "repo_name": repo_name,
                "file_path": "README.md",
                "new_content": f"""# {repo_name}

Generated by AWOS.

## Mission

{description}

## Status

Completed
""",
                "commit_message": "Update README",
                "branch": "feature/awos",
            },
        )

        actions.append(update["message"])

        # ------------------------------------------------
        # 5. Create Pull Request
        # ------------------------------------------------

        pr = await mcp_manager.call(
            server="github",
            tool="create_repository_pull_request",
            arguments={
                "owner": owner,
                "repo_name": repo_name,
                "title": "Initial Implementation",
                "body": "Generated automatically by AWOS.",
                "head_branch": "feature/awos",
                "base_branch": "main",
            },
        )

        actions.append(pr["message"])

        return EngineerResult(
            completed=True,
            actions=actions,
        )
