"""
planner.py

AWOS Mission Planner

The Planner (CEO Agent) analyzes the user's objective and
creates an execution plan for the GitHub workflow.

Responsibilities
----------------
• Detect mission type
• Determine GitHub actions
• Provide execution metadata
"""

from typing import Dict, List


def create_execution_plan(query: str) -> Dict:
    """
    Create an execution plan for the mission.

    Parameters
    ----------
    query : str
        User objective.

    Returns
    -------
    dict
    """

    query_lower = query.lower()

    mission_type = "research"

    actions: List[str] = []

    owner = ""
    repo_name = ""
    file_path = "README.md"
    content = "# Updated by AWOS"

    # -------------------------------------------------
    # Repository Creation Mission
    # -------------------------------------------------
    if any(word in query_lower for word in [

        "create",
        "build",
        "new repository",
        "new repo",
        "generate",
        "initialize"

    ]):

        mission_type = "repository_creation"

        actions = [

            "create_repository",
            "create_file",
            "create_branch",
            "review"

        ]

    # -------------------------------------------------
    # Repository Update Mission
    # -------------------------------------------------
    elif any(word in query_lower for word in [

        "update",
        "modify",
        "edit",
        "change",
        "improve",
        "enhance",
        "refactor"

    ]):

        mission_type = "repository_update"

        actions = [

            "update_file",
            "create_pull_request",
            "review"

        ]

        # -----------------------------------------
        # Simple parsing
        #
        # Example:
        # Update awos-core README
        # -----------------------------------------

        words = query.split()

        if len(words) >= 2:
            repo_name = words[1]

        if "readme" in query_lower:
            file_path = "README.md"

        content = (
            "# Updated by AWOS\n\n"
            "Automated update generated by the Engineer Agent."
        )

    # -------------------------------------------------
    # Research Mission
    # -------------------------------------------------
    else:

        mission_type = "research"

        actions = [

            "search_repositories",
            "get_repository",
            "get_readme",
            "search_code",
            "review"

        ]

    # -------------------------------------------------
    # Priority
    # -------------------------------------------------

    priority = "Medium"

    if "urgent" in query_lower or "critical" in query_lower:
        priority = "High"

    elif "minor" in query_lower:
        priority = "Low"

    # -------------------------------------------------
    # Estimated Complexity
    # -------------------------------------------------

    if mission_type == "research":

        complexity = "Low"

    elif mission_type == "repository_creation":

        complexity = "Medium"

    else:

        complexity = "High"

    # -------------------------------------------------
    # Return execution plan
    # -------------------------------------------------

    return {

        "status": "success",

        "objective": query,

        "mission_type": mission_type,

        "priority": priority,

        "complexity": complexity,

        "planned_actions": actions,

        "estimated_steps": len(actions),

        "owner": owner,

        "repo_name": repo_name,

        "file_path": file_path,

        "content": content

    }


if __name__ == "__main__":

    from pprint import pprint

    pprint(

        create_execution_plan(

            "Create a FastAPI authentication project"

        )

    )

    pprint(

        create_execution_plan(

            "Update awos-core README"

        )

    )

    pprint(

        create_execution_plan(

            "Find the best authentication library for FastAPI"

        )

    )
