"""
=========================================================
Module      : client.py

System      : AWOS

Component   : AI

Purpose
-------
Defines the abstract interface for every
Large Language Model supported by AWOS.

Author
------
Project AWOS Team

Version
-------
Genesis v1.0
=========================================================
"""

from abc import ABC, abstractmethod


class AIClient(ABC):
    """
    Abstract base class for every LLM client.
    """

    @abstractmethod
    def generate(self, prompt: str) -> str:
        """
        Generate a response from the language model.

        Parameters
        ----------
        prompt : str
            Prompt sent to the LLM.

        Returns
        -------
        str
            Raw response generated by the model.
        """

        pass
