import anyio

from app.agents.engineer import EngineerAgent


async def main():

    engineer = EngineerAgent()

    result = await engineer.execute(
        repo_name="awos-engineer-demo",
        description="Repository generated by Engineer Agent",
    )

    print(result.model_dump())


if __name__ == "__main__":
    anyio.run(main)
